name: "\U0001F41B Bug report"
description: "Report a bug with this project."
title: "[Bug]: "
labels: ["bug"]
assignees:
  - asdek
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  Please fill in as much of the template below as you can.
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please write a clear and concise description of the bug, including what you expect to happen and what is currently happening.
      placeholder: |
        Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please write the steps needed to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots, screen recording, code snippet
      description: |
        If possible, please upload a screenshot or screen recording which demonstrates the bug. You can use [LICEcap](https://www.cockos.com/licecap/) to create a GIF screen recording.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        For small snippets paste it directly here, or you can use [GitHub Gist](https://gist.github.com) to share multiple code files.
        Please ensure the shared code can be used by a developer to reproduce the issue—ideally it can be copied into a local development environment or executed in a browser console to help debug the issue
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment information
      placeholder: |
        - UI server version: <!-- [e.g. 3.2.0] -->
        - Agent server version: <!-- [e.g. 3.2.0] -->
        - Agent version: <!-- [e.g. 3.2.0] -->
        - Module version: <!-- [e.g. 1.0.1] -->
        - Link Module code: <!-- [link-to-zip-archive-with-helpful-code] -->
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which agent binary used?
      description: We have several different builds, choose which ones have the problem.
      options:
        - label: darwin-amd64
        - label: linux-386
        - label: linux-amd64
        - label: windows-386
        - label: windows-amd64
    validations:
      required: true
