shape: sequence_diagram

browser; server; SQLite; agent

browser.a -> server.a: Action: scan\n(filename)
server.a -> SQLite: New task
server.a -> agent.a: Request file\n(task_id, filename)
browser <- server.a: Notify about new task
server.b <- agent.a: Receive file\n(task_id)
server.b -> SQLite: Update task\n(hash)
server.b -> Cuckoo: POST file
server.b -> SQLite: Update task\n(scanning)

SQLite {shape: cylinder}
