browser <- user: |
	1. Provide filename
	2. Click "Scan"
|
browser -> server: 3. Send action
agent <- server: 4. Send action
agent -> server: 5. Send file
server -> sqlite: 6. INSERT new task
# browser <- server: 7: Notify about new task?
server -> cuckoo: 8. POST file

user: "" {shape: person; width: 80; height: 80}
browser {
	shape: image
	icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
	height: 80
}
sqlite: "" {
	shape: image
	icon: https://www.sqlite.org/images/sqlite370_banner.gif
	height: 80
}
cuckoo: "" {
	shape: image
	icon: https://cuckoosandbox.org/assets/images/cuckoo-black.png
	height: 80
}

# direction: right
